### PR TITLE
.off(event, fn) removes duplicate handlers 

### PR DESCRIPTION
**Pull request by duzun**
1. .off() should remove in reverse order;
2. .off(event, fn) should remove all occurrences of fn.

### CODE REVIEW

**Comment by jonathanong** [comment]
i'm not sure i see a reason for 1). i do not think 2) is incorrect. your first and last commits are not relevant. 

if you could provide a more thorough test-case/example for this, that would be really helpful!

**Comment by duzun** [comment]
There are two reasons for 1):
a. .off() should be symmetric with .on() (like push/pop), so that in the case you decide to remove only one instance of fn, it should remove the last added fn.
b. when removing multiple consecutive instances of fn (same callback added twice or more times), you should do it in reverse order, otherwise you are going to skip some of them (just run the test from commit  0cd27ec on original `index.js` - it will fail).

2) it is difficult to come up with a real life example where you'll have some callback added twice with .on(), and not being as a result of bad application design. But IMO after a call to .off(event, fn), fn should be gone for good!

*First commit explained*: after installing devDependencies i've got an `npm-debug.log` - I don't think this file should be part of the repo. So I decided to add it to `.gitignore`

*Last commit explained*: I'm going to use this library in a browser environment and the line
```module.exports = Emitter;```
will just break the code.
With [UMD](https://github.com/umdjs/umd) this module can be run in any environment.

**Comment by jonathanong** [comment]
not entirely convinced. i'll wait until some other owners add their 2 cents.

**Comment by stephenmathieson** [comment]
i think the `.off(e, fn)` change makes sense, but i'm not sure how necessary it is

big -1 on the umd stuff

**Comment by vendethiel** [comment]
If you still need this, please ping with a commit that only does this.

Thanks & sorry for the delay.

**Pull request closed without merging**
